## Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation

In [1]:
import torch
import numpy as np

### Initializing a Tensor
Tensors can be initialized in various ways.

#### Directly from data

Tensors can be created directly from data. The data type is automatically inferred

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


#### From a NumPy array

Tensors can be created from NumPy arrays

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


#### From another tensor:
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5836, 0.8897],
        [0.9567, 0.2163]]) 



#### With random or constant values:

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [7]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9922, 0.1265, 0.1408],
        [0.2110, 0.2555, 0.2313]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [11]:
tensor = torch.rand(3,4)
print(f"Random Tensor: \n {tensor} \n")
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Random Tensor: 
 tensor([[0.9264, 0.8415, 0.9363, 0.7744],
        [0.3684, 0.7556, 0.6529, 0.3377],
        [0.0218, 0.9406, 0.4923, 0.8310]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors
Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are possible wth tensors. Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Copying large tensors across devices can be expensive in terms of time and memory!

In [12]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

#### Standard numpy-like indexing and slicing:

In [24]:
tensor = torch.rand(3,4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last row: {tensor[-1]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)
tensor[1,:] = 0
print(tensor)

tensor([[0.1901, 0.5748, 0.4446, 0.4256],
        [0.4732, 0.4647, 0.9292, 0.6002],
        [0.5548, 0.5557, 0.3808, 0.7313]])
First row: tensor([0.1901, 0.5748, 0.4446, 0.4256])
First column: tensor([0.1901, 0.4732, 0.5548])
Last row: tensor([0.5548, 0.5557, 0.3808, 0.7313])
Last column: tensor([0.4256, 0.6002, 0.7313])
tensor([[0.1901, 0.0000, 0.4446, 0.4256],
        [0.4732, 0.0000, 0.9292, 0.6002],
        [0.5548, 0.0000, 0.3808, 0.7313]])
tensor([[0.1901, 0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313]])


#### Joining tensors 
You can use `torch.cat` to concatenate a sequence of tensors along a given dimension.

In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t2)

tensor([[0.1901, 0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313],
        [0.1901, 0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313],
        [0.1901, 0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313]])
tensor([[0.1901, 0.0000, 0.4446, 0.4256, 0.1901, 0.0000, 0.4446, 0.4256, 0.1901,
         0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313, 0.5548, 0.0000, 0.3808, 0.7313, 0.5548,
         0.0000, 0.3808, 0.7313]])


### Arithmetic operations

In [40]:
print(tensor)
y1 = tensor@tensor.T            # the @ operator represents matrix multiplication
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(y1)        # generates a tensor y3 with the same shape as y1, but with random values sampled from a uniform distribution in the range [0,1]
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.1901, 0.0000, 0.4446, 0.4256],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.5548, 0.0000, 0.3808, 0.7313]])
tensor([[0.4149, 0.0000, 0.5860],
        [0.0000, 0.0000, 0.0000],
        [0.5860, 0.0000, 0.9876]])
tensor([[0.4149, 0.0000, 0.5860],
        [0.0000, 0.0000, 0.0000],
        [0.5860, 0.0000, 0.9876]])


tensor([[0.4149, 0.0000, 0.5860],
        [0.0000, 0.0000, 0.0000],
        [0.5860, 0.0000, 0.9876]])

In [41]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0361, 0.0000, 0.1976, 0.1812],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3078, 0.0000, 0.1450, 0.5348]])
tensor([[0.0361, 0.0000, 0.1976, 0.1812],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3078, 0.0000, 0.1450, 0.5348]])


tensor([[0.0361, 0.0000, 0.1976, 0.1812],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3078, 0.0000, 0.1450, 0.5348]])

#### Single-element tensors 
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using `item()`:

In [44]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(2.7271)
2.7271173000335693 <class 'float'>


#### In-place operations 
Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix. For example: `x.copy_(y)`, `x.t_()`, will change x.

In [49]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[5.1901, 5.0000, 5.5548],
        [5.0000, 5.0000, 5.0000],
        [5.4446, 5.0000, 5.3808],
        [5.4256, 5.0000, 5.7313]]) 

tensor([[10.1901, 10.0000, 10.5548],
        [10.0000, 10.0000, 10.0000],
        [10.4446, 10.0000, 10.3808],
        [10.4256, 10.0000, 10.7313]])


### Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

#### Tensor to NumPy array

In [50]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [51]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor

In [52]:
n = np.ones(4)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1.]


Changes in the NumPy array reflects in the tensor.

In [53]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2.]
